receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

  prometheus:
    config:
      scrape_configs:
        - job_name: 'django'
          static_configs:
            - targets: ['13.125.14.13:8000']  # Adjust to your Django app's host:port
          metrics_path: /metrics

processors:
  batch:
    timeout: 10s
    send_batch_size: 1000


exporters:
  clickhouse:
    endpoint: "tcp://clickhouse:9000?dial_timeout=15s&compress=lz4"
    username: "clickhouse"
    password: "clickhouse" # CHANGEME
    database: "django"
    async_insert: true
    logs_table_name: "django_logs"
    traces_table_name: "otel_traces" # Optional: If you plan to send traces
    timeout: 15s
    create_schema: true
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s
    table_engine:
      name: MergeTree

  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: "django"
    send_timestamps: true
    metric_expiration: 180m

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouse]
    traces:  # Optional: If you plan to send traces
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouse]
    metrics:
      receivers: [prometheus]
      processors: [batch]
      exporters: [prometheus]
