global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9095']
  
  - job_name: 'langfuse'
    static_configs:
      - targets: ['langfuse-web:3000', 'langfuse-worker:3030']
  
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
  
  - job_name: 'django-app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['127.0.0.1:8000']
        labels:
          group: 'server'
